# Generated by Django 5.2.7 on 2025-11-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='categorias',
        ),
        migrations.AddField(
            model_name='role',
            name='comisiones',
            field=models.IntegerField(choices=[(0, 'No tiene accesso'), (1, 'Ver Solo'), (2, 'Crear y Modificar')], default=0),
        ),
        migrations.AddField(
            model_name='role',
            name='empresas',
            field=models.IntegerField(choices=[(0, 'No tiene accesso'), (1, 'Ver Solo'), (2, 'Crear y Modificar')], default=0),
        ),
        migrations.AddField(
            model_name='role',
            name='equipos',
            field=models.IntegerField(choices=[(0, 'No tiene accesso'), (1, 'Ver Solo'), (2, 'Crear y Modificar')], default=0),
        ),
        migrations.AddField(
            model_name='role',
            name='regla_comisiones',
            field=models.IntegerField(choices=[(0, 'No tiene accesso'), (1, 'Ver Solo'), (2, 'Crear y Modificar')], default=0),
        ),
    ]
